# Generated by Django 4.1.4 on 2023-04-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(
                help_text="Required",
                max_length=255,
                unique=True,
                verbose_name="Product Type",
            ),
        ),
    ]
