# Generated by Django 4.1.4 on 2023-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_producttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional",
                max_length=255,
                verbose_name="description",
            ),
        ),
    ]
