# Generated by Django 4.1.4 on 2023-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {
                        "max_length": "The price should be between 0 and 9999999999.99"
                    }
                },
                help_text="Maximum 9999999999.99",
                max_digits=12,
                verbose_name="Discount price",
            ),
        ),
    ]
