# Generated by Django 4.1.4 on 2023-04-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
