# Generated by Django 4.1.4 on 2023-04-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_productimage_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
