# Generated by Django 4.1.4 on 2023-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_line2",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Address line 2"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line",
            field=models.CharField(max_length=255, verbose_name="Address line 1"),
        ),
    ]
