# Generated by Django 4.1.4 on 2023-04-25 15:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_address_address_line2_alter_address_address_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country",
            field=django_countries.fields.CountryField(default="NG", max_length=2),
            preserve_default=False,
        ),
    ]
