# Generated by Django 4.1.4 on 2023-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_address_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="town_city",
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="city", max_length=150, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(
                default="state", max_length=150, verbose_name="State"
            ),
            preserve_default=False,
        ),
    ]
