# Generated by Django 4.1.4 on 2023-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_name",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        verbose_name="delivery name",
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        error_messages={
                            "name": {
                                "max_length": "price must be between 0 and 9999999999.99"
                            }
                        },
                        help_text="Maximum 9999999999.99",
                        max_digits=12,
                        verbose_name="delivery price",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("PU", "Pick Up"),
                            ("HD", "Home Delivery"),
                            ("ID", "International Delivery"),
                        ],
                        help_text="Required",
                        max_length=255,
                        verbose_name="delivery method",
                    ),
                ),
                (
                    "delivery_timeframe",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        verbose_name="Delivery timeframe",
                    ),
                ),
                (
                    "delivery_window",
                    models.CharField(
                        help_text="Required",
                        max_length=255,
                        verbose_name="Delivery window",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Required", verbose_name="list_order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Delivery Option",
                "verbose_name_plural": "Delivery Options",
            },
        ),
        migrations.CreateModel(
            name="PaymentSelections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required", max_length=255, verbose_name="Name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Payment Selection",
                "verbose_name_plural": "Payment Selections",
            },
        ),
    ]
