# Generated by Django 4.1.4 on 2023-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardno',
            field=models.CharField(default='nil', max_length=4),
        ),
    ]
