# Generated by Django 4.1.4 on 2023-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cardno',
            field=models.CharField(max_length=4),
        ),
    ]
