# Generated by Django 4.1.4 on 2023-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "orders",
            "0005_remove_order_address1_remove_order_address2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="address1",
            field=models.CharField(default="Johnny Lane", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="address2",
            field=models.CharField(default="Agip", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="PH", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="country_code",
            field=models.CharField(
                blank=True, max_length=4, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default="08103863127", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default="500262", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(default="Port Harcourt", max_length=100),
            preserve_default=False,
        ),
    ]
